name: Full Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install Trunk
        run: cargo install trunk

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Backend tests
        run: cargo test --manifest-path backend/Cargo.toml

      - name: Frontend tests
        run: cargo test --manifest-path frontend/Cargo.toml

      - name: Build and serve the application
        run: |
          cd frontend
          trunk build
          trunk serve --port 3000 &
        env:
          SERVER_PID: $!

      - name: Run Wasm-pack tests on build application
        run: wasm-pack test --headless --chrome --firefox
        env:
          SERVER_PID: ${{ env.SERVER_PID }}

      - name: Stop server
        run: kill ${{ env.SERVER_PID }}
