name: Full Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo test --manifest-path backend/Cargo.toml
      - run: cargo test --manifest-path frontend/Cargo.toml
      - run: cd frontend
      - run: wasm-pack test --headless --chrome --manifest-path frontend/Cargo.toml
      - run: wasm-pack test --headless --firefox --manifest-path frontend/Cargo.toml
